# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# title: Neuroanatomy & Connectivity Lab
title: Cognitive Neuroanatomy Lab
email: daniel.margulies@cnrs.fr

url: "https://www.neuroconnlab.org"
baseurl: "" # the subpath of your site, e.g. /blog

twitter_username: neuro_conn
github_username:  NeuroanatomyAndConnectivity

# Build settings
markdown: kramdown
theme: minima

# Include future posts
future: true

# Jekyll scholar
plugins_dir: ['jekyll/scholar']
# Load plugins
plugins: ['jekyll/scholar', 'unicode_utils', 'unicode', 'jekyll-sitemap', 'jekyll-target-blank']

scholar:
  style: ./bibcsl/acta_small.csl
  locale: en

  sort_by: year
  order: descending
  bibliography_list_tag: ul

  group_by: none
  group_order: descending

  source: ./_bibliography
  bibliography: publications.bib
  bibliography_template: bib

  replace_strings: true
  join_strings:    true
  sort_by:         year, month

  use_raw_bibtex_entry: false
  bibtex_filters:
  - superscript
  - latex

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"

include:
  - _redirects

exclude:
  - README.md
  - _TODO.md
  - Gemfile
  - Gemfile.lock
  - _CV/
  - _fachbeirat/
  - _videos/
  - Makefile
  - bibcsl/ieee.csl
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - workspace.code-workspace

defaults:
  - scope:
      path: "downloads/pubs/*.pdf"
    values:
      sitemap: false
  - scope:
      path: "downloads/press/*.pdf"
    values:
      sitemap: false
  - scope:
      path: "downloads/people/CV_Margulies.pdf"
    values:
      sitemap: false

navigation: 
  - title: Research
    url: /research/index.html
    subnav:
      - text: Projects
        url: /research/index.html
      - text: Publications
        url: /research/publications.html
      - text: Press
        url: /press/index.html  
  - title: Members  
    url: #  
    subnav:  
      - text: Current  
        url: /members/current.html  
      - text: Former  
        url: /members/former.html  
      - text: Collaborators  
        url: /members/collaborators.html  
  - title: Resources
    url: #
    subnav:      
      - text: Data
        url: /data/index.html
      - text: Code
        url: /code/index.html
      - text: Gallery
        url: /gallery/index.html
      - text: Miscellaneous
        url: /resources/index.html
  - title: Contact
    url: /contact/index.html
  # - title: Join us
  #   url: /jobs/index.html

  # - title: Quick Links
  #   url: #
  #   subnav:
  #     - text: Gradient templates
  #       url: /data/index.html#maps
  #     - text: MPILBMM dataset
  #       url: /data/index.html#MPILBMM

jekyll_admin:
  hidden_links:
    - posts
    - datafiles      
  # homepage: "/"